name: Upload OW_IP Scripts to Discord

on:
  push:
    branches:
      - main

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare list of files to upload
        id: files
        shell: bash
        run: |
          FILES="OW_IP.BAT OW_IP_Scrapper.ps1"
          echo "Files to upload: $FILES"

          # Check if files exist
          MISSING=0
          for F in $FILES; do
            if [ ! -f "$F" ]; then
              echo "File $F not found!"
              MISSING=1
            fi
          done

          if [ $MISSING -eq 1 ]; then
            echo "Some files are missing. Exiting."
            echo "files_found=false" >> $GITHUB_OUTPUT
          else
            echo "All files found."
            echo "files_found=true" >> $GITHUB_OUTPUT
            echo "files_list=$FILES" >> $GITHUB_OUTPUT

      - name: Send files to all Discord webhooks dynamically
        if: steps.files.outputs.files_found == 'true'
        shell: bash
        run: |
          FILES="${{ steps.files.outputs.files_list }}"
          echo "Uploading files: $FILES"

          # Detect all webhook secrets
          WEBHOOK_VARS=$(compgen -v | grep '^DISCORD_WEBHOOK_')

          if [ -z "$WEBHOOK_VARS" ]; then
            echo "No Discord webhook secrets found. Exiting."
            exit 0
          fi

          for VAR_NAME in $WEBHOOK_VARS; do
            WEBHOOK=${!VAR_NAME}
            echo "Sending files to $VAR_NAME..."

            CURL_FILES=""
            for FILE in $FILES; do
              CURL_FILES+="-F file[]=@./$FILE "
            done

            curl -H "Content-Type: multipart/form-data" \
                 -F "payload_json={\"content\": \"Repo updated → sending OW_IP files\"}" \
                 $CURL_FILES \
                 "$WEBHOOK" || true

            echo "Files sent successfully to $VAR_NAME."
          done
