name: Upload OW_IP Scripts to Discord

on:
  push:
    branches:
      - main

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Upload each script to Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        FILES=$(git ls-files '*.ps1' '*.bat')

        if [ -z "$FILES" ]; then
          echo "No .ps1 or .bat files found."
          exit 0
        fi

        for FILE in $FILES; do
          echo "Uploading $FILE..."
          curl -H "Content-Type: multipart/form-data" \
               -F "payload_json={\"content\": \"Repo updated → sending $FILE\"}" \
               -F "file=@$FILE;type=application/octet-stream" \
               "$DISCORD_WEBHOOK"
          echo "$FILE uploaded successfully."
        done
