name: Upload OW_IP Scripts to Discord

on:
  push:
    branches:
      - main  # run on push to main branch

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Send files to Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}  # set your webhook in repo secrets
      run: |
        # Change to folder containing the scripts
        cd OW_IP_scrap

        # Make sure files exist
        if [[ ! -f OW_IP_Scrapper.ps1 || ! -f OW_IP.bat ]]; then
          echo "Required files not found!"
          exit 1
        fi

        # Send both files with a message
        curl -H "Content-Type: multipart/form-data" \
             -F "payload_json={\"content\": \"Repo updated → sending OW_IP_Scrapper.ps1 and OW_IP.bat\"}" \
             -F "file[]=@OW_IP_Scrapper.ps1" \
             -F "file[]=@OW_IP.bat" \
             "$DISCORD_WEBHOOK"
