name: Upload OW_IP Scripts to Discord

on:
  push:
    branches:
      - main

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if root files exist
        shell: bash
        id: detect_files
        run: |
          FILES="OW_IP.BAT OW_IP_Scrapper.ps1"
          echo "Files to upload: $FILES"

          # Check if files exist
          MISSING=0
          for F in $FILES; do
            if [ ! -f "$F" ]; then
              echo "File $F not found!"
              MISSING=1
            fi
          done

          if [ $MISSING -eq 1 ]; then
            echo "Some files are missing. Exiting."
            echo "files_found=false" >> $GITHUB_OUTPUT
          else
            echo "All files found."
            echo "files_found=true" >> $GITHUB_OUTPUT
            echo "files_list=$FILES" >> $GITHUB_OUTPUT
          fi

      - name: Upload files to Discord webhooks
        if: steps.detect_files.outputs.files_found == 'true'
        shell: bash
        run: |
          FILES="${{ steps.detect_files.outputs.files_list }}"
          echo "Uploading files: $FILES"

          # Detect all webhook secrets dynamically
          WEBHOOK_VARS=$(compgen -v | grep '^DISCORD_WEBHOOK_')

          for VAR_NAME in $WEBHOOK_VARS; do
            WEBHOOK=${!VAR_NAME}
            echo "Sending files to $VAR_NAME..."

            # Send each file individually to avoid parsing issues
            for FILE in $FILES; do
              echo "Uploading $FILE to $VAR_NAME..."
              curl -H "Content-Type: multipart/form-data" \
                   -F "payload_json={\"content\": \"Repo updated → sending $FILE\"}" \
                   -F "file=@./$FILE;type=application/octet-stream" \
                   "$WEBHOOK" || true
            done

            echo "Files sent successfully to $VAR_NAME."
          done
