name: Upload OW_IP Scripts to Discord

on:
  push:
    branches:
      - main  # or your target branch

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   # fetch full history to avoid HEAD^ errors

    - name: Find and upload .ps1 and .bat files
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        # Find all .ps1 and .bat files in repo
        FILES=$(git ls-files '*.ps1' '*.bat')
        
        if [ -z "$FILES" ]; then
          echo "No .ps1 or .bat files found to upload."
          exit 0
        fi

        # Build curl command
        CURL_CMD="curl -H 'Content-Type: multipart/form-data' \
          -F 'payload_json={\"content\": \"Repo updated → sending scripts\"}'"

        for FILE in $FILES; do
          CURL_CMD="$CURL_CMD -F file[]=@$FILE"
        done

        CURL_CMD="$CURL_CMD \"$DISCORD_WEBHOOK\""

        # Run the curl command
        eval $CURL_CMD
