name: Upload OW_IP Scripts to Discord

on:
  push:
    branches:
      - main

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if target files changed
        id: check_files
        run: |
          # List files in the last commit
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)
          echo "Changed files: $CHANGED_FILES"
          
          if echo "$CHANGED_FILES" | grep -qE '^(OW_IP_Scrapper\.ps1|OW_IP\.BAT)$'; then
            echo "files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "files_changed=false" >> $GITHUB_OUTPUT

      - name: Send both files in a single message to multiple Discord webhooks
        if: steps.check_files.outputs.files_changed == 'true'
        env:
          DISCORD_WEBHOOKS: ${{ secrets.DISCORD_WEBHOOKS }}
        run: |
          if [[ -z "$DISCORD_WEBHOOKS" ]]; then
            echo "No Discord webhooks defined. Exiting..."
            exit 0
          fi

          # Split the comma-separated webhooks into an array
          IFS=',' read -ra WEBHOOK_ARRAY <<< "$DISCORD_WEBHOOKS"
          
          # Send both files to each webhook
          for WEBHOOK in "${WEBHOOK_ARRAY[@]}"; do
            echo "Uploading OW_IP.BAT and OW_IP_Scrapper.ps1 to $WEBHOOK..."
            
            # Check if files exist
            if [[ ! -f OW_IP.BAT || ! -f OW_IP_Scrapper.ps1 ]]; then
              echo "One or both files are missing. Skipping this webhook."
              continue
            fi

            curl -H "Content-Type: multipart/form-data" \
                 -F "payload_json={\"content\": \"Repo updated → sending OW_IP_Scrapper.ps1 and OW_IP.BAT\"}" \
                 -F "file1=@OW_IP.BAT" \
                 -F "file2=@OW_IP_Scrapper.ps1" \
                 "$WEBHOOK"
          done
